name: Parallel Sleep Jobs

on:
  push:
    branches: [concurrency]

jobs:
  parallel-sleep:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        iteration:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
    name: Sleep Job #${{ matrix.iteration }}
    steps:
      - name: Sleep for 1 minute
        run: sleep 60
